export const equityIndexMapDisplaySet = [
  { color: "#2E4D70", name: "High" },
  { color: "#47719F", name: "Medium-High" },
  { color: "#84B3E0", name: "Medium" },
  { color: "#AECFED", name: "Medium-Low" },
  { color: "#DCEBFB", name: "Low" },
];

export const countyWithColor = [
  {
    countyId: "53001",
    eq: 84,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 8031,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53003",
    eq: 73,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 1803,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53005",
    eq: 83,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 60501,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53007",
    eq: 67,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 15465,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53009",
    eq: 54,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 8978,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53011",
    eq: 88,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 100890,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53013",
    eq: 85,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 544,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53015",
    eq: 72,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 10302,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53017",
    eq: 84,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 13791,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53019",
    eq: 80,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 1756,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53021",
    eq: 75,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 47311,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53023",
    eq: 73,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 225,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53025",
    eq: 70,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 38708,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53027",
    eq: 73,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 9270,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53029",
    eq: 84,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 13947,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53031",
    eq: 75,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 3242,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53033",
    eq: 98,
    eqColorHex: "#2E4D70",
    eqValueId: "high",
    ethnicityId: "bipoc",
    population: 988591,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53035",
    eq: 85,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 53932,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53037",
    eq: 77,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 6457,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53039",
    eq: 75,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 1841,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53041",
    eq: 50,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 8321,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53043",
    eq: 74,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 727,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53045",
    eq: 69,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 9695,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53047",
    eq: 82,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 11990,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53049",
    eq: 78,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 3478,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53051",
    eq: 76,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 1665,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53053",
    eq: 92,
    eqColorHex: "#47719F",
    eqValueId: "high_medium",
    ethnicityId: "bipoc",
    population: 329092,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53055",
    eq: 78,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 1510,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53057",
    eq: 76,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 28217,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53059",
    eq: 78,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 884,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53061",
    eq: 97,
    eqColorHex: "#47719F",
    eqValueId: "high_medium",
    ethnicityId: "bipoc",
    population: 281730,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53063",
    eq: 76,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 87253,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53065",
    eq: 75,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 4820,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53067",
    eq: 90,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 58867,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53069",
    eq: 85,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 499,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53071",
    eq: 80,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 11102,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53073",
    eq: 81,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 36907,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53075",
    eq: 78,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 9466,
    stateId: "53",
    type: "COUNTY",
  },
  {
    countyId: "53077",
    eq: 67,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 135441,
    stateId: "53",
    type: "COUNTY",
  },
];

export const stateWithColor = [
  {
    eq: 88,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 1756335,
    stateId: "01",
    type: "STATE",
  },
  {
    eq: 72,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 297669,
    stateId: "02",
    type: "STATE",
  },
  {
    eq: 92,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 3034647,
    stateId: "04",
    type: "STATE",
  },
  {
    eq: 89,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 898230,
    stateId: "05",
    type: "STATE",
  },
  {
    eq: 90,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 23794060,
    stateId: "06",
    type: "STATE",
  },
  {
    eq: 90,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 1710686,
    stateId: "08",
    type: "STATE",
  },
  {
    eq: 97,
    eqColorHex: "#47719F",
    eqValueId: "high_medium",
    ethnicityId: "bipoc",
    population: 1249539,
    stateId: "09",
    type: "STATE",
  },
  {
    eq: 99,
    eqColorHex: "#2E4D70",
    eqValueId: "high",
    ethnicityId: "bipoc",
    population: 389825,
    stateId: "10",
    type: "STATE",
  },
  {
    eq: 67,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 414774,
    stateId: "11",
    type: "STATE",
  },
  {
    eq: 95,
    eqColorHex: "#47719F",
    eqValueId: "high_medium",
    ethnicityId: "bipoc",
    population: 9570389,
    stateId: "12",
    type: "STATE",
  },
  {
    eq: 98,
    eqColorHex: "#2E4D70",
    eqValueId: "high",
    ethnicityId: "bipoc",
    population: 5191785,
    stateId: "13",
    type: "STATE",
  },
  {
    eq: 94,
    eqColorHex: "#47719F",
    eqValueId: "high_medium",
    ethnicityId: "bipoc",
    population: 1117039,
    stateId: "15",
    type: "STATE",
  },
  {
    eq: 81,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 351109,
    stateId: "16",
    type: "STATE",
  },
  {
    eq: 96,
    eqColorHex: "#47719F",
    eqValueId: "high_medium",
    ethnicityId: "bipoc",
    population: 4894727,
    stateId: "17",
    type: "STATE",
  },
  {
    eq: 91,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 1495778,
    stateId: "18",
    type: "STATE",
  },
  {
    eq: 88,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 496379,
    stateId: "19",
    type: "STATE",
  },
  {
    eq: 92,
    eqColorHex: "#47719F",
    eqValueId: "high_medium",
    ethnicityId: "bipoc",
    population: 701989,
    stateId: "20",
    type: "STATE",
  },
  {
    eq: 85,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 747967,
    stateId: "21",
    type: "STATE",
  },
  {
    eq: 82,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 1945195,
    stateId: "22",
    type: "STATE",
  },
  {
    eq: 87,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 130397,
    stateId: "23",
    type: "STATE",
  },
  {
    eq: 100,
    eqColorHex: "#2E4D70",
    eqValueId: "high",
    ethnicityId: "bipoc",
    population: 3142740,
    stateId: "24",
    type: "STATE",
  },
  {
    eq: 88,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 2150422,
    stateId: "25",
    type: "STATE",
  },
  {
    eq: 90,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 2610286,
    stateId: "26",
    type: "STATE",
  },
  {
    eq: 94,
    eqColorHex: "#47719F",
    eqValueId: "high_medium",
    ethnicityId: "bipoc",
    population: 1268629,
    stateId: "27",
    type: "STATE",
  },
  {
    eq: 86,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 1295377,
    stateId: "28",
    type: "STATE",
  },
  {
    eq: 92,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 1385070,
    stateId: "29",
    type: "STATE",
  },
  {
    eq: 79,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 158982,
    stateId: "30",
    type: "STATE",
  },
  {
    eq: 89,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 422578,
    stateId: "31",
    type: "STATE",
  },
  {
    eq: 88,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 1583981,
    stateId: "32",
    type: "STATE",
  },
  {
    eq: 89,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 165972,
    stateId: "33",
    type: "STATE",
  },
  {
    eq: 96,
    eqColorHex: "#47719F",
    eqValueId: "high_medium",
    ethnicityId: "bipoc",
    population: 4200578,
    stateId: "34",
    type: "STATE",
  },
  {
    eq: 90,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 1159503,
    stateId: "35",
    type: "STATE",
  },
  {
    eq: 83,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 8803262,
    stateId: "36",
    type: "STATE",
  },
  {
    eq: 94,
    eqColorHex: "#47719F",
    eqValueId: "high_medium",
    ethnicityId: "bipoc",
    population: 3957794,
    stateId: "37",
    type: "STATE",
  },
  {
    eq: 84,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 117636,
    stateId: "38",
    type: "STATE",
  },
  {
    eq: 87,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 2662932,
    stateId: "39",
    type: "STATE",
  },
  {
    eq: 95,
    eqColorHex: "#47719F",
    eqValueId: "high_medium",
    ethnicityId: "bipoc",
    population: 1369581,
    stateId: "40",
    type: "STATE",
  },
  {
    eq: 90,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 1076708,
    stateId: "41",
    type: "STATE",
  },
  {
    eq: 91,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 3254849,
    stateId: "42",
    type: "STATE",
  },
  {
    eq: 80,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 315126,
    stateId: "44",
    type: "STATE",
  },
  {
    eq: 89,
    eqColorHex: "#84B3E0",
    eqValueId: "medium",
    ethnicityId: "bipoc",
    population: 1887527,
    stateId: "45",
    type: "STATE",
  },
  {
    eq: 78,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 171973,
    stateId: "46",
    type: "STATE",
  },
  {
    eq: 86,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 1871599,
    stateId: "47",
    type: "STATE",
  },
  {
    eq: 97,
    eqColorHex: "#2E4D70",
    eqValueId: "high",
    ethnicityId: "bipoc",
    population: 15398191,
    stateId: "48",
    type: "STATE",
  },
  {
    eq: 87,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 690234,
    stateId: "49",
    type: "STATE",
  },
  {
    eq: 67,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 44485,
    stateId: "50",
    type: "STATE",
  },
  {
    eq: 99,
    eqColorHex: "#2E4D70",
    eqValueId: "high",
    ethnicityId: "bipoc",
    population: 3382832,
    stateId: "51",
    type: "STATE",
  },
  {
    eq: 93,
    eqColorHex: "#47719F",
    eqValueId: "high_medium",
    ethnicityId: "bipoc",
    population: 2599244,
    stateId: "53",
    type: "STATE",
  },
  {
    eq: 83,
    eqColorHex: "#DCEBFB",
    eqValueId: "low",
    ethnicityId: "bipoc",
    population: 153899,
    stateId: "54",
    type: "STATE",
  },
  {
    eq: 86,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 1163154,
    stateId: "55",
    type: "STATE",
  },
  {
    eq: 84,
    eqColorHex: "#AECFED",
    eqValueId: "medium_low",
    ethnicityId: "bipoc",
    population: 77523,
    stateId: "56",
    type: "STATE",
  },
];
